python3 run_qa.py \
  --model_name_or_path burakaytan/roberta-base-turkish-uncased \
  --dataset_name ./squad_tr \
  --do_train \
  --do_eval \
  --per_device_train_batch_size 12 \
  --learning_rate 3e-5 \ 
  --num_train_epochs 100 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir roberta-eval-strategy/ \
  --evaluation_strategy steps